#!/bin/bash

STATE_FILE="/tmp/i3block_time_state"

[ ! -f "$STATE_FILE" ] && echo "time" > "$STATE_FILE"

if [ "$BLOCK_BUTTON" == "1" ]; then
  current=$(cat "$STATE_FILE")
  if [ "$current" = "time" ]; then
    echo "date" > "$STATE_FILE"
  else
    echo "time" > "$STATE_FILE"
  fi

  pkill -RTMIN+1 i3blocks
fi

if [ "$(cat "$STATE_FILE")" = "date" ]; then
  date "+%A, %B %d %Y %r"
else
  date "+%r"
fi
